### ISSUE TITLE
Logic for figuring out next player to play is incorrect

### ISSUE THREAD

**Issue by nitinsurana** [jacobhyphenated/PokerServer#21] opened 2015-12-16 18:04 UTC
Consider this :

1. Player 1 bets
2. Player 2 bets
3. Player 1 calls
4. HAND COMPLETE
5. Player 2's turn, but the software says it's player 1's turn.

**Comment by jacobhyphenated** [comment] 2015-12-16 18:31
@nitinsurana I believe this is a duplicate of issue #10 .  As currently written, the services does not handle the end of a betting round and requires the game client to end the hand or deal the next card.

**Closed** 2015-12-19 10:16 UTC
